baseURL = "https://eureka1029.github.io/"
locale = "zh-cn"
title = "YongHao Ning"
theme = "archie"
copyright = "© Eureka"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = ""
  favicon = "/favicon.svg"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Eureka1029"

[[params.social]]
name = "Bilibili"
icon = "simple:bilibili"
url = "https://space.bilibili.com/326517598"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Search"
url = "/search/"
weight = 5
